# Copyright (C) 2016  ParadoxSpiral
#
# This file is part of mpv-sys.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

[package]
name = "libmpv-sys"
version = "3.1.0"
edition = "2018"
authors = ["ParadoxSpiral <ParadoxSpiral@riseup.net>"]
license = "LGPL-2.1"
build = "build.rs"
description = "Libmpv bindings generated by bindgen"
repository = "https://github.com/ParadoxSpiral/libmpv-rs"
keywords = ["media", "playback", "mpv", "libmpv"]

[build-dependencies.bindgen]
version = "0.54"
optional = true

# Workaround for https://github.com/rust-lang/rust-bindgen/issues/1313
[lib]
doctest = false

[features]
# You can either use the pregenerated bindings, or gen new ones with bindgen
use-bindgen = ["bindgen"]
