name: CI

on:
    workflow_dispatch:
    push:
      branches:
        - "main"
      paths-ignore:
        - "docs/**"
        - "**/.gitignore"
        - "**/.dockerignore"
        - LICENSE
        - "**/*.md"
    pull_request:
      branches:
        - "main"
      paths-ignore:
        - "docs/**"
        - "**/.gitignore"
        - "**/.dockerignore"
        - LICENSE
        - "**/*.md"

jobs:
  linux:
    uses: ./.github/workflows/build_linux.yml
    secrets: inherit

  windows:
    uses: ./.github/workflows/build_windows.yml
    secrets: inherit

  upload:
    runs-on: ubuntu-latest
    needs: [linux, windows]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Zip artifact
        id: zip
        run: |
          echo "zip_files<<EOF" >> "$GITHUB_OUTPUT"
          find artifacts/ -mindepth 1 -maxdepth 1 -type d | while read -r dir; do
            zip -r "${dir}.zip" "$dir"
            echo "${dir}.zip"
          done >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Start Telegram Bot API
        run: | 
          docker run -d -p 8081:8081 \
          --name=telegram-bot-api \
          -e TELEGRAM_API_ID=${{ secrets.TELEGRAM_API_ID }} \
          -e TELEGRAM_API_HASH=${{ secrets.TELEGRAM_API_HASH }} \
          aiogram/telegram-bot-api:latest

      - name: Wait for Telegram Bot API to be ready
        run: |
          while ! curl -s -f -o /dev/null http://localhost:8081; do
            echo "Waiting for Telegram Bot API..."
            sleep 5
          done
          echo "Telegram Bot API is ready!"

      - name: Upload to Telegram
        uses: nyaruta/tg-file-action@v0.2.0
        with:
          api-url: 'http://localhost:8081'
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat-id: ${{ secrets.TELEGRAM_CHAT_ID }}
          files: ${{ steps.zip.outputs.zip_files }}
          body: 'Tsukimi CI\nCommit Message: ${{ github.event.head_commit.message}}\nCommit URL: ${{ github.event.head_commit.url }}'



        
    